### ISSUE TITLE
Upload library to pub hub?

### ISSUE THREAD

**Issue by abc873693** [douasin/big5-dart#1]
I use your library, but your dart version is too old for support flutter.
Can you upload to pub hub?
https://pub.dev/

**Comment by douasin** [comment]
hi, sorry for reply late that I didn't get any notification from github
 it's has been a long time since I write dart, I'm not family with the current dart environment, how to do that?

**Comment by abc873693** [comment]
Do you install dart environment?
I see the dart pub has the latest updates.
Have this auto publish?

**Comment by douasin** [comment]
I didn't install the newest dart environment.
I only merged ur PR and run the publish command.

**Comment by abc873693** [comment]
OK , may be add CI/CD test to confirm PR build correct.
Package is working normally
